#!/bin/bash

. /bin/.datamap_config

VERMONT_CONFIG_FILE=/bin/vermont_config.xml
TMP_FILE=/bin/vermont_config.xml.tmp

# Location of aircrack-ng binaries
AIRMON_NG="/usr/local/sbin/airmon-ng"
AIRODUMP_NG="/usr/local/sbin/airodump-ng"

# Populate the vermont config file with values from our config file
cp $VERMONT_CONFIG_FILE $TMP_FILE
cat /bin/.datamap_config | while read line
do
	name=`echo $line | sed s/=.*//`
	val=`echo $line | sed s/.*=//`
	sed -i s/\{$name\}/$val/ $TMP_FILE
done

# Set up the monitor interface
${AIRMON_NG} stop mon0 # Ensures that we will start monitoring through mon0
${AIRMON_NG} start wlan0

# Start the encrypted network parser
df3_data_parser.py /dev/shm/cap-01.csv $wpa2_essid &

# Start airodump-ng
rm -f /dev/shm/cap-01.*
screen -S airodump -d -m ${AIRODUMP_NG} -t OPN -t WPA2 -w /dev/shm/cap  mon0

# Start vermont
vermont -f /bin/vermont_config.xml.tmp -ddd "$@" > /var/log/vermont.out.log 2> /var/log/vermont.err.log
