#!/bin/bash

VERMONT_CONFIG_FILE=/bin/vermont_config.xml
TMP_FILE=/bin/vermont_config.xml.tmp

cp $VERMONT_CONFIG_FILE $TMP_FILE

cat /bin/.datamap_config | while read line
do
	name=`echo $line | sed s/=.*//`
	val=`echo $line | sed s/.*=//`
	echo $name = $val
	sed -i s/\{$name\}/$val/ $TMP_FILE
done

vermont -f /bin/vermont_config.xml.tmp