#!/bin/bash

TMP_FILE=/bin/vermont_config.xml.tmp

# Stop vermont
killall vermont

# Stop airodump-ng
screen -S airodump -X quit

# Take down the monitor interface
airmon-ng stop mon0

# Remove the temporary config file
rm -f TMP_FILE